spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://h2:1521/~/test
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  batch:
    jdbc:
      initialize-schema: always
#    job:
#      name: systemTerminationSimulationJob
logging:
  level:
    org.springframework.batch: DEBUG
